default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trk
  username: trk
  password: trk

test:
  <<: *default
  database: trk
  username: trk
  password: trk

production:
  <<: *default
  database: trk
  username: trk
  password: <%= ENV['TRKTEST_DATABASE_PASSWORD'] %>
